package com.prueba.testingdm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class persona implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public persona() {
    }




}